import Link from "next/link";
import Image from "next/image";
import { cases, certifications, industries, products } from "@/data/site";
import { SectionHeading } from "@/components/SectionHeading";
import { TrackedLink } from "@/components/TrackedLink";

export default function Home() { return <>
  <section className="hero-glow brand-grid relative min-h-[660px] overflow-hidden py-24 text-white md:flex md:min-h-[760px] md:items-center"><div className="absolute right-[7%] top-1/2 hidden h-[420px] w-[420px] -translate-y-1/2 rounded-full border border-blue-300/20 lg:block"><div className="absolute inset-12 rounded-full border border-blue-300/20"/><div className="absolute inset-24 rounded-full bg-blue-500/10 blur-xl"/></div><div className="container-site relative"><div className="mb-8 flex items-center gap-4 text-[11px] font-bold tracking-[.22em] text-blue-300"><span>01</span><span className="h-px w-20 bg-blue-400"/><span>SEKWANG C&amp;H</span></div><p className="text-sm font-bold tracking-[.12em] text-blue-200">UNMATCHED QUALITY, ABSOLUTE TRUST</p><h1 className="mt-5 max-w-5xl text-[2.65rem] font-black leading-[1.1] tracking-[-.055em] md:text-7xl">상업용 냉장·냉동·온장<br/><span className="text-blue-300">쇼케이스 전문기업</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-slate-200 md:text-lg">1991년부터 이어온 제조 경험으로 냉장·냉동부터 온장까지,<br className="hidden md:block"/> 업종과 현장에 맞는 종합 온도관리 솔루션을 제안합니다.</p><div className="mt-10 flex flex-wrap gap-3"><a href="#industries" className="btn btn-primary">내 업종에 맞는 제품 찾기 <span className="ml-4">→</span></a><TrackedLink href="/contact" event="consultation_click" label="hero" className="btn border border-white/30 text-white hover:bg-white/10">상담·견적 문의</TrackedLink><TrackedLink href="tel:031-945-4204" event="phone_click" label="hero" className="btn text-blue-200">031-945-4204~6</TrackedLink></div></div></section>
  <section id="industries" className="section"><div className="container-site"><SectionHeading eyebrow="Find your solution" title="제품이 아닌, 운영하는 업종에서 시작하세요" description="매장마다 필요한 온도와 진열 방식은 다릅니다. 가장 가까운 업종을 선택하면 필요한 정보만 빠르게 확인할 수 있습니다."/><div className="grid border-l border-t border-slate-200 sm:grid-cols-2 lg:grid-cols-5">{industries.map((x,i)=><TrackedLink key={x.id} href={x.href} event="industry_card_click" label={x.id} className="group min-h-72 border-b border-r border-slate-200 bg-white p-7 transition hover:bg-[#081b3c] hover:text-white"><div className="flex items-center justify-between"><span className="text-xs font-black tracking-widest text-blue-600">0{i+1}</span><span className="text-xl text-blue-500 transition group-hover:translate-x-1">↗</span></div><h3 className="mt-20 text-2xl font-black group-hover:text-white">{x.name}</h3><p className="mt-4 text-sm leading-6 text-slate-500 group-hover:text-blue-100">{x.description}</p></TrackedLink>)}</div></div></section>
  <section className="section bg-slate-50"><div className="container-site"><SectionHeading eyebrow="두 가지 안내" title="찾는 목적에 따라 필요한 정보를 나눴습니다"/><div className="grid gap-5 md:grid-cols-2"><Solution title="일반 쇼케이스" who="식당 · 정육점 · 카페·베이커리" body="가격 결정 기준, 설치와 A/S, 업종별 추천 제품군을 쉽게 확인하세요." href="/solutions/general"/><Solution title="특수 쇼케이스" who="의료기관 · 참치·수산물 전문점" body="온도관리 요구, 성능·인증자료 확인 절차와 전문 상담을 안내합니다." href="/solutions/special"/></div></div></section>
  <section id="products" className="section"><div className="container-site"><SectionHeading eyebrow="Featured products" title="세광시앤에이치의 대표 제품군" description="공식 제품 분류를 바탕으로 구성했습니다. 상세 사양은 실제 설치 조건을 확인한 후 안내합니다."/><div className="grid gap-px bg-slate-200 sm:grid-cols-2 lg:grid-cols-5">{products.map((x,i)=><article className="group bg-white p-7" key={x.name}><div className="relative flex h-40 items-center justify-center overflow-hidden bg-slate-50"><span className="absolute left-4 top-4 text-xs font-bold text-slate-400">0{i+1}</span><Image src={x.image} alt="" width={180} height={130} className="max-h-28 w-auto object-contain transition duration-500 group-hover:scale-105"/></div><p className="mt-6 text-[10px] font-bold uppercase tracking-[.16em] text-blue-600">{x.english}</p><h3 className="mt-2 text-xl font-black">{x.name}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{x.description}</p></article>)}</div></div></section>
  <section id="cases" className="section bg-slate-50"><div className="container-site"><SectionHeading eyebrow="대표 설치사례" title="비슷한 업종의 적용 방향을 확인하세요" description="아래 항목은 레이아웃 검증을 위한 샘플 콘텐츠이며 실제 설치자료로 교체해야 합니다."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cases.map((x,i)=><article className="card" key={i}><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">샘플 콘텐츠</span><h3 className="mt-5 text-xl font-black">{x.industry}</h3><dl className="mt-4 grid grid-cols-[6rem_1fr] gap-y-2 text-sm"><dt className="text-slate-500">설치 제품</dt><dd>{x.product}</dd><dt className="text-slate-500">지역</dt><dd>{x.region}</dd></dl></article>)}</div></div></section>
  <section id="trust" className="section"><div className="container-site"><SectionHeading eyebrow="회사 신뢰정보" title="오랜 경험과 품질경영의 기반"/><div className="grid gap-4 md:grid-cols-3"><article className="card bg-[#071d3b] text-white"><p className="text-4xl font-black text-blue-300">1991</p><h3 className="mt-2 font-bold">설립</h3><p className="mt-5 text-sm text-blue-100">상업용 온도관리 분야의 경험을 이어왔습니다.</p></article><article className="card md:col-span-2"><p className="font-bold text-slate-500">확인된 인증</p><div className="mt-5 flex flex-wrap gap-3">{certifications.map(x=><span className="rounded-lg bg-blue-50 px-4 py-3 font-black text-blue-800" key={x}>{x}</span>)}</div><p className="mt-6 text-sm text-slate-600">주요 기업 및 프랜차이즈 납품 경험 · 구체 납품처와 수치는 운영자료 확인 후 공개</p></article></div></div></section>
  <section className="section bg-blue-600 text-white"><div className="container-site text-center"><p className="text-blue-100">어떤 제품이 맞는지 몰라도 괜찮습니다</p><h2 className="mt-3 text-3xl font-black md:text-4xl">업종과 설치 지역부터 알려주세요</h2><p className="mx-auto mt-4 max-w-xl text-blue-100">담당자가 사용 환경을 확인하고 다음 선택을 안내합니다.</p><TrackedLink href="/contact" event="consultation_click" label="home_final" className="btn mt-7 bg-white text-blue-700">상담 시작하기</TrackedLink></div></section>
  </> }

function Solution({title,who,body,href}:{title:string;who:string;body:string;href:string}) { return <article className="card p-7 md:p-9"><p className="font-bold text-blue-600">{who}</p><h3 className="mt-3 text-3xl font-black">{title}</h3><p className="mt-4 leading-7 text-slate-600">{body}</p><Link href={href} className="btn btn-primary mt-7">맞춤 안내 보기</Link></article> }
