import Link from "next/link";
import { cases, certifications, industries, products } from "@/data/site";
import { SectionHeading } from "@/components/SectionHeading";
import { TrackedLink } from "@/components/TrackedLink";

export default function Home() { return <>
  <section className="relative overflow-hidden bg-[#071d3b] py-20 text-white md:py-28"><div className="absolute -right-24 top-10 h-80 w-80 rounded-full bg-blue-500/20 blur-3xl"/><div className="container-site relative"><p className="eyebrow !text-blue-300">Cold &amp; Hot · Total temperature management</p><h1 className="mt-5 max-w-4xl text-4xl font-black leading-tight tracking-[-.04em] md:text-6xl">매장과 현장에 맞는<br/><span className="text-blue-300">상업용 냉장·냉동·온장 쇼케이스</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-blue-100">세광시앤에이치는 업종과 사용 환경부터 살펴 알맞은 쇼케이스 선택을 돕는 전문기업입니다.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#industries" className="btn btn-primary">내 업종에 맞는 제품 찾기</a><TrackedLink href="/contact" event="consultation_click" label="hero" className="btn btn-secondary">상담·견적 문의</TrackedLink><span className="btn border border-white/20 text-blue-100">전화번호 확인 필요</span></div></div></section>
  <section id="industries" className="section"><div className="container-site"><SectionHeading eyebrow="업종별 찾기" title="제품명보다 내 업종에서 시작하세요" description="운영 환경이 다르면 필요한 쇼케이스 정보도 달라집니다. 가장 가까운 업종을 선택해 보세요."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{industries.map((x,i)=><TrackedLink key={x.id} href={x.href} event="industry_card_click" label={x.id} className="card group block"><span className="text-sm font-black text-blue-600">0{i+1}</span><h3 className="mt-6 text-xl font-black group-hover:text-blue-600">{x.name}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{x.description}</p><span className="mt-5 inline-block font-bold text-blue-700">살펴보기 →</span></TrackedLink>)}</div></div></section>
  <section className="section bg-slate-50"><div className="container-site"><SectionHeading eyebrow="두 가지 안내" title="찾는 목적에 따라 필요한 정보를 나눴습니다"/><div className="grid gap-5 md:grid-cols-2"><Solution title="일반 쇼케이스" who="식당 · 정육점 · 카페·베이커리" body="가격 결정 기준, 설치와 A/S, 업종별 추천 제품군을 쉽게 확인하세요." href="/solutions/general"/><Solution title="특수 쇼케이스" who="의료기관 · 참치·수산물 전문점" body="온도관리 요구, 성능·인증자료 확인 절차와 전문 상담을 안내합니다." href="/solutions/special"/></div></div></section>
  <section id="products" className="section"><div className="container-site"><SectionHeading eyebrow="대표 제품군" title="운영 목적에 맞춰 선택하는 쇼케이스" description="검증되지 않은 상세 사양은 표시하지 않았습니다. 실제 조건은 상담을 통해 확인합니다."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{products.map((x,i)=><article className="card" key={x.name}><div className="grid h-12 w-12 place-items-center rounded-xl bg-blue-50 font-black text-blue-700">{i+1}</div><h3 className="mt-5 text-lg font-black">{x.name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{x.description}</p></article>)}</div></div></section>
  <section id="cases" className="section bg-slate-50"><div className="container-site"><SectionHeading eyebrow="대표 설치사례" title="비슷한 업종의 적용 방향을 확인하세요" description="아래 항목은 레이아웃 검증을 위한 샘플 콘텐츠이며 실제 설치자료로 교체해야 합니다."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cases.map((x,i)=><article className="card" key={i}><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">샘플 콘텐츠</span><h3 className="mt-5 text-xl font-black">{x.industry}</h3><dl className="mt-4 grid grid-cols-[6rem_1fr] gap-y-2 text-sm"><dt className="text-slate-500">설치 제품</dt><dd>{x.product}</dd><dt className="text-slate-500">지역</dt><dd>{x.region}</dd></dl></article>)}</div></div></section>
  <section id="trust" className="section"><div className="container-site"><SectionHeading eyebrow="회사 신뢰정보" title="오랜 경험과 품질경영의 기반"/><div className="grid gap-4 md:grid-cols-3"><article className="card bg-[#071d3b] text-white"><p className="text-4xl font-black text-blue-300">1991</p><h3 className="mt-2 font-bold">설립</h3><p className="mt-5 text-sm text-blue-100">상업용 온도관리 분야의 경험을 이어왔습니다.</p></article><article className="card md:col-span-2"><p className="font-bold text-slate-500">확인된 인증</p><div className="mt-5 flex flex-wrap gap-3">{certifications.map(x=><span className="rounded-lg bg-blue-50 px-4 py-3 font-black text-blue-800" key={x}>{x}</span>)}</div><p className="mt-6 text-sm text-slate-600">주요 기업 및 프랜차이즈 납품 경험 · 구체 납품처와 수치는 운영자료 확인 후 공개</p></article></div></div></section>
  <section className="section bg-blue-600 text-white"><div className="container-site text-center"><p className="text-blue-100">어떤 제품이 맞는지 몰라도 괜찮습니다</p><h2 className="mt-3 text-3xl font-black md:text-4xl">업종과 설치 지역부터 알려주세요</h2><p className="mx-auto mt-4 max-w-xl text-blue-100">담당자가 사용 환경을 확인하고 다음 선택을 안내합니다.</p><TrackedLink href="/contact" event="consultation_click" label="home_final" className="btn mt-7 bg-white text-blue-700">상담 시작하기</TrackedLink></div></section>
  </> }

function Solution({title,who,body,href}:{title:string;who:string;body:string;href:string}) { return <article className="card p-7 md:p-9"><p className="font-bold text-blue-600">{who}</p><h3 className="mt-3 text-3xl font-black">{title}</h3><p className="mt-4 leading-7 text-slate-600">{body}</p><Link href={href} className="btn btn-primary mt-7">맞춤 안내 보기</Link></article> }
