import { cases, faqs } from "@/data/site";
import { FeedbackForm } from "./FeedbackForm";
import { PageView } from "./PageView";
import { SectionHeading } from "./SectionHeading";
import { TrackedLink } from "./TrackedLink";

type Segment={id:string;name:string;concerns:string[];products:string[]};
export function SolutionLayout({type,title,lead,segments,special=false}:{type:"general"|"special";title:string;lead:string;segments:Segment[];special?:boolean}) { const event=type==="general"?"general_solution_view":"special_solution_view"; return <>
  <PageView event={event}/><section className="hero-glow brand-grid relative overflow-hidden py-24 text-white md:py-32"><div className="container-site"><div className="mb-8 flex items-center gap-4 text-[11px] font-bold tracking-[.2em] text-blue-300"><span>{special?"SPECIAL SOLUTION":"GENERAL SOLUTION"}</span><span className="h-px w-20 bg-blue-400"/></div><h1 className="max-w-5xl text-4xl font-black leading-[1.12] tracking-[-.05em] md:text-6xl">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-200">{lead}</p><div className="mt-10 flex flex-wrap gap-3">{segments.map(x=><a key={x.id} href={`#${x.id}`} className="btn border border-white/30 text-white hover:bg-white hover:text-slate-900">{x.name} <span className="ml-4">↓</span></a>)}</div></div></section>
  <section className="section"><div className="container-site"><SectionHeading eyebrow="업종 선택" title="내 현장과 가까운 업종부터 확인하세요"/><div className={`grid gap-5 ${segments.length===3?"md:grid-cols-3":"md:grid-cols-2"}`}>{segments.map(s=><article id={s.id} className="card scroll-mt-24" key={s.id}><h2 className="text-2xl font-black">{s.name}</h2><h3 className="mt-6 font-bold text-blue-700">주요 고민</h3><ul className="mt-3 grid gap-2 text-slate-600">{s.concerns.map(x=><li key={x}>✓ {x}</li>)}</ul><h3 className="mt-6 font-bold text-blue-700">추천 제품군</h3><p className="mt-3 text-slate-600">{s.products.join(" · ")}</p><p className="mt-5 rounded-lg bg-slate-50 p-3 text-xs text-slate-500">세부 제품과 사양은 설치 조건 확인 후 안내합니다.</p></article>)}</div></div></section>
  {special ? <SpecialEvidence/> : <GeneralGuide/>}
  <section className="section bg-slate-50"><div className="container-site"><SectionHeading eyebrow="대표 사례" title="업종별 설치사례" description="현재 카드는 화면 검증용 샘플이며 실제 납품·설치자료로 교체해야 합니다."/><div className="grid gap-4 md:grid-cols-3">{cases.filter(c=>special?["의료기관","참치·수산물 전문점"].includes(c.industry):!["의료기관","참치·수산물 전문점"].includes(c.industry)).map((c,i)=><article key={i} className="card"><span className="text-xs font-bold text-amber-700">샘플 콘텐츠</span><h3 className="mt-3 text-xl font-black">{c.industry}</h3><p className="mt-3 text-sm text-slate-600">{c.product} · {c.region}</p></article>)}</div></div></section>
  <section className="section bg-[#0a1b39] text-center text-white"><div className="container-site"><p className="eyebrow !text-blue-300">Talk to our expert</p><h2 className="mt-4 text-3xl font-black md:text-5xl">{special?"전문 담당자와 요구조건을 확인하세요":"내 매장에 맞는 선택을 함께 정리하세요"}</h2><p className="mt-5 text-slate-300">제품을 정하지 않아도 업종과 설치 예정 지역만으로 상담을 시작할 수 있습니다.</p><TrackedLink href="/contact" event="consultation_click" label={`${type}_final`} className="btn btn-primary mt-8">상담·견적 문의 <span className="ml-4">→</span></TrackedLink></div></section><FeedbackForm page={type}/>
  </> }

function GeneralGuide(){return <section className="section bg-blue-50"><div className="container-site"><SectionHeading eyebrow="구매 전 안내" title="가격부터 설치 이후까지 확인하세요"/><div className="grid gap-4 md:grid-cols-3">{[["가격 결정 방식","제품 유형, 크기, 설치 환경과 주문 사양에 따라 달라집니다. 정확한 값은 담당자 확인 필요."],["설치 안내","설치 가능 지역과 예상 기간은 현장과 제품에 따라 달라 담당자 확인 필요."],["A/S 안내","적용 정책과 처리 절차는 제품 및 지역에 따라 담당자 확인 필요."]].map(x=><article className="card" key={x[0]}><h3 className="text-xl font-black">{x[0]}</h3><p className="mt-3 leading-7 text-slate-600">{x[1]}</p></article>)}</div><div className="mt-10"><h3 className="text-2xl font-black">구매 전 FAQ</h3><div className="mt-5 grid gap-3">{faqs.map(f=><details className="card" key={f.q}><summary className="cursor-pointer font-bold">{f.q}</summary><p className="mt-3 leading-7 text-slate-600">{f.a}</p></details>)}</div></div></div></section>}
function SpecialEvidence(){return <section className="section bg-blue-50"><div className="container-site"><SectionHeading eyebrow="검증 자료" title="정밀한 판단에 필요한 자료를 투명하게 확인합니다"/><div className="grid gap-5 md:grid-cols-2"><article className="card"><h3 className="text-xl font-black">제품 성능자료</h3><p className="mt-3 text-slate-600">온도 범위, 시험성적, 성능 수치 등 관련 자료 확인 중</p><div className="mt-6 rounded-xl border border-dashed border-blue-300 bg-blue-50 p-8 text-center text-sm text-blue-700">검증된 성능자료가 들어갈 영역</div></article><article className="card"><h3 className="text-xl font-black">업종별 인증자료</h3><p className="mt-3 text-slate-600">의료기관용 인증 및 특수 용도 관련 자료 확인 중</p><div className="mt-6 rounded-xl border border-dashed border-blue-300 bg-blue-50 p-8 text-center text-sm text-blue-700">검증된 인증자료가 들어갈 영역</div></article></div></div></section>}
